// Code generated by lesiw.io/testdetect. DO NOT EDIT.
package main

import (
	"fmt"
	"testing"
)

var testingDetectorCovHack bool

func init() { testingDetectorInit() }
func testingDetectorInit() {
	if got, want := (testingDetector{}).Testing(), testing.Testing(); testingDetectorCovHack || got != want {
		panic(fmt.Sprintf("bad testingDetector state: got %t, want %t", got, want))
	}
}

type testingDetector struct{ testingDetectorEmbed }
type testingDetectorEmbed struct{}

func (t testingDetectorEmbed) Testing() bool { return false }

var _ = (testingDetector{}).testingDetectorEmbed
